=== isabella232/m2-content-provisioning/etc/content_provisioning.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                    <xs:element type="page" name="page"/>
                    <xs:element type="block" name="block"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueCode">
            <xs:annotation>
                <xs:documentation>
                    Entries must have unique code
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="page|block"/>
            <xs:field xpath="@key"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="page">
        <xs:choice maxOccurs="unbounded">
            <xs:element minOccurs="1" maxOccurs="1" type="content" name="content"/>
            <xs:element minOccurs="1" maxOccurs="1" name="title">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="media_directory">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" type="stores" name="stores"/>
            <xs:element minOccurs="0" maxOccurs="1" type="seo" name="seo"/>
            <xs:element minOccurs="0" maxOccurs="1" type="design" name="design"/>
            <xs:element minOccurs="0" maxOccurs="1" type="custom_design" name="custom_design"/>
        </xs:choice>
        <xs:attribute name="key" type="key" use="required"/>
        <xs:attribute name="identifier" type="identifier" use="required"/>
        <xs:attribute name="active" type="xs:boolean" use="required"/>
        <xs:attribute name="maintained" type="xs:boolean" use="optional"/>
    </xs:complexType>

    <xs:complexType name="seo">
        <xs:choice maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" type="xs:string" name="title"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:string" name="keywords"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:string" name="description"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="design">
        <xs:choice maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" type="layout" name="layout"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:string" name="layout_xml"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="custom_design">
        <xs:choice maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" type="xs:date" name="from"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:date" name="to"/>
            <xs:element minOccurs="0" maxOccurs="1" type="xs:integer" name="theme_id"/>
            <xs:element minOccurs="0" maxOccurs="1" type="layout" name="layout"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="block">
        <xs:choice maxOccurs="unbounded">
            <xs:element minOccurs="0" maxOccurs="1" type="stores" name="stores"/>
            <xs:element minOccurs="1" maxOccurs="1" type="content" name="content"/>
            <xs:element minOccurs="0" maxOccurs="1" name="media_directory">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="1" maxOccurs="1" type="xs:string" name="title"/>
        </xs:choice>
        <xs:attribute name="key" type="key" use="required"/>
        <xs:attribute name="identifier" type="identifier" use="required"/>
        <xs:attribute name="active" type="xs:boolean" use="required"/>
        <xs:attribute name="maintained" type="xs:boolean" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="key">
        <xs:annotation>
            <xs:documentation>
                Unique code for cms entities
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_\\\-\.]{1,}"/>
            <xs:minLength value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="identifier">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_\\\-]{1,}"/>
            <xs:minLength value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="stores">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" type="store" name="store"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="store">
        <xs:attribute name="code" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="content">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="content_type" use="optional"/>
                <xs:attribute name="heading" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="content_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="file"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="layout">
        <xs:restriction base="xs:string">
            <xs:enumeration value="empty"/>
            <xs:enumeration value="1column"/>
            <xs:enumeration value="2columns-left"/>
            <xs:enumeration value="2columns-right"/>
            <xs:enumeration value="3columns"/>
            <xs:enumeration value="cms-full-width"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== isabella232/m2-content-provisioning/Test/Integration/Model/Config/_files/content_provisioning.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Firegento_ContentProvisioning:etc/content_provisioning.xsd">
    <page key="test.page.1" identifier="test-page-1" maintained="true" active="true">
        <title>Test Page 1</title>
        <content type="file">Firegento_ContentProvisioning::Test/Integration/Model/Config/_files/test-files/file-1.html</content>
    </page>
    <page key="test.page.2" identifier="test-page-2" active="false">
        <title>Title 2</title>
        <content heading="New Page Heading 2" type="file">Firegento_ContentProvisioning::Test/Integration/Model/Config/_files/test-files/file-1.html</content>
        <stores>
            <store code="default"/>
            <store code="admin"/>
        </stores>
        <seo>
            <title>SEO Page Title</title>
            <keywords>Some, SEO, keywords</keywords>
            <description>SEO description</description>
        </seo>
        <design>
            <layout>3columns</layout>
            <layout_xml><![CDATA[<foo>bar</foo>]]></layout_xml>
        </design>
        <custom_design>
            <from>2019-03-03</from>
            <to>2019-03-29</to>
            <layout>3columns</layout>
            <theme_id>3</theme_id>
        </custom_design>
    </page>
    <page key="test.page.3" identifier="test-page-3" active="true" maintained="true">
        <title>Page With Images</title>
        <content type="file">Firegento_ContentProvisioning::Test/Integration/Model/Config/_files/test-files/content-with-images-1.html</content>
        <media_directory>Firegento_ContentProvisioning::Test/Integration/Model/Config/_files/test-files/media</media_directory>
    </page>
    <block key="test.block.1" identifier="test-block-1" maintained="true" active="true">
        <title>Test Block 1</title>
        <content><![CDATA[<h2>test foobar Aenean commodo ligula eget dolor aenean massa</h2>]]></content>
    </block>
    <block key="test.block.2" identifier="test-block-2" maintained="false" active="true">
        <title>Test Block 2</title>
        <content type="file">Firegento_ContentProvisioning::Test/Integration/Model/Config/_files/test-files/file-1.html</content>
        <stores>
            <store code="default"/>
            <store code="admin"/>
        </stores>
    </block>
    <block key="test.block.3" identifier="test-block-3" maintained="true" active="true">
        <title>Block With Images</title>
        <content type="file">Firegento_ContentProvisioning::Test/Integration/Model/Config/_files/test-files/content-with-images-1.html</content>
        <media_directory>Firegento_ContentProvisioning::Test/Integration/Model/Config/_files/test-files/media</media_directory>
    </block>
</config>
